// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_get_dashboard from "./routes/api/get-dashboard.ts";
import * as $api_set_dashboard from "./routes/api/set-dashboard.ts";
import * as $auth_index from "./routes/auth/index.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $index from "./routes/index.tsx";
import * as $Card from "./islands/Card.tsx";
import * as $Modal from "./islands/Modal.tsx";
import * as $PayingSetup from "./islands/PayingSetup.tsx";
import * as $PayingSetupCard from "./islands/PayingSetupCard.tsx";
import * as $PayingSetupList from "./islands/PayingSetupList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/get-dashboard.ts": $api_get_dashboard,
    "./routes/api/set-dashboard.ts": $api_set_dashboard,
    "./routes/auth/index.ts": $auth_index,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Card.tsx": $Card,
    "./islands/Modal.tsx": $Modal,
    "./islands/PayingSetup.tsx": $PayingSetup,
    "./islands/PayingSetupCard.tsx": $PayingSetupCard,
    "./islands/PayingSetupList.tsx": $PayingSetupList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
